[package]
name = "weechat-discord"
version = "0.2.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[lib]
name = "weecord"
crate-type = ["dylib"]

[features]
default = ["onig"]

pcre = ["parsing/pcre"]
onig = ["parsing/onig"]

[dependencies]
libc = "0.2.60"
parking_lot = "0.9.0"
lazy_static = "1.3.0"
dirs = "2.0.1"
crossbeam-channel = "0.3.9"
json = "0.11.14"

[dependencies.serenity]
git = "https://github.com/terminal-discord/serenity"
branch = "current"
default_features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
]

[dependencies.parsing]
path = "parsing"

[dependencies.weechat]
# path = "../rust-weechat/weechat-rs"
git = "https://github.com/terminal-discord/rust-weechat"
rev = "a8d831f"

[dependencies.weechat-sys]
git = "https://github.com/terminal-discord/rust-weechat"
rev = "a8d831f"
