[package]
name = "weecord"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>", "khyperia <khyperia@live.com>", "Noskcaj <kcajdev@gmail.com>"]
build = "build.rs"
edition = "2018"

[build-dependencies]
pkg-config = "0.3.14"
cc = "1.0.32"

[lib]
name = "weecord"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.51"
lazy_static = "1.3.0"
dirs = "1.0.5"
crossbeam-channel = "0.3.8"
serde_json = "1.0.39"

[dependencies.serenity]
git = "https://github.com/terminal-discord/serenity"
branch = "v0.6.x"
default_features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
]

[dependencies.parsing]
path = "parsing"
