[package]
name = "weechat-discord"
version = "0.3.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[lib]
name = "weecord"
crate-type = ["cdylib"]

[features]
default = ["onig"]

pcre = ["parsing/pcre"]
onig = ["parsing/onig"]
weecord-debug = ["accountable-refcell"]

[dependencies.parsing]
path = "parsing"

[dependencies]
glob = "0.3.0"
dirs = "3.0.1"
libc = "0.2.77"
anyhow = "1.0.32"
tracing = "0.1.19"
regex = "1.3.9"
chrono = "0.4.15"
once_cell = "1.4.1"
futures = "0.3.5"
parking_lot = "0.11.0"

[dependencies.accountable-refcell]
version = "0.2.0"
optional = true

[dependencies.tracing-subscriber]
version = "0.2.12"
default_features = false
features = ["fmt", "ansi", "smallvec", "env-filter"]

[dependencies.make_rs]
git = "https://github.com/Noskcaj19/make_rs"

[dependencies.tokio]
version = "0.2.22"
features = ["rt-threaded", "sync", "macros"]

[dependencies.weechat]
git = "https://github.com/terminal-discord/rust-weechat"
branch = "mk3"
features = ["async", "unsound"]

[dependencies.weechat-sys]
git = "https://github.com/terminal-discord/rust-weechat"
branch = "mk3"

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = ["std"]

[dependencies.twilight-cache-inmemory]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-gateway]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-http]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-model]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-mention]
git = "https://github.com/terminal-discord/twilight"
branch = "next"
