[package]
name = "weechat-discord"
version = "0.3.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[lib]
name = "weecord"
crate-type = ["cdylib"]

[features]
default = ["onig"]

pcre = ["parsing/pcre"]
onig = ["parsing/onig"]
weecord-debug = ["accountable-refcell"]

[dependencies.parsing]
path = "parsing"

[dependencies]
glob = "0.3.0"
dirs = "3.0.1"
libc = "0.2.79"
anyhow = "1.0.33"
tracing = "0.1.21"
regex = "1.4.1"
chrono = "0.4.19"
once_cell = "1.4.1"
futures = "0.3.6"
parking_lot = "0.11.0"

[dependencies.discord-emoji]
git = "https://github.com/terminal-discord/discord-emoji"
branch = "main"

[dependencies.serde]
version = "1.0.117"
features = ["derive"]

[dependencies.accountable-refcell]
version = "0.2.0"
optional = true

[dependencies.tracing-subscriber]
version = "0.2.13"
default_features = false
features = ["fmt", "ansi", "smallvec", "env-filter"]

[dependencies.make_rs]
git = "https://github.com/Noskcaj19/make_rs"

[dependencies.weechat-command-parser]
git = "https://github.com/terminal-discord/weechat-command-parser"

[dependencies.tokio]
version = "0.2.22"
features = ["rt-threaded", "sync", "macros"]

[dependencies.weechat]
git = "https://github.com/terminal-discord/rust-weechat"
branch = "mk3"
features = ["async", "unsound"]

[dependencies.weechat-sys]
git = "https://github.com/terminal-discord/rust-weechat"
branch = "mk3"

[dependencies.twilight-cache-inmemory]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-gateway]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-http]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-model]
git = "https://github.com/terminal-discord/twilight"
branch = "next"

[dependencies.twilight-mention]
git = "https://github.com/terminal-discord/twilight"
branch = "next"
