[package]
name = "weechat-discord"
version = "0.3.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[lib]
name = "weecord"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.71"
glob = "0.3.0"
dirs = "2.0.2"
anyhow = "1.0.31"
tracing = "0.1.14"
regex = "1.3.9"


[dependencies.tracing-subscriber]
version = "0.2.5"
default_features = false
features = ["fmt", "ansi", "smallvec"]

[dependencies.make_rs]
git = "https://github.com/Noskcaj19/make_rs"

[dependencies.tokio]
version = "0.2.21"
features = ["rt-threaded", "sync"]

[dependencies.weechat]
git = "https://github.com/terminal-discord/rust-weechat"
branch = "mk3"
features = ["async-executor", "unstable"]

[dependencies.weechat-sys]
git = "https://github.com/terminal-discord/rust-weechat"
branch = "mk3"

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = ["std"]

[dependencies.serenity]
git = "https://github.com/terminal-discord/serenity"
branch = "mk3"
default_features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "utils",
    "rustls_backend",
]
