[package]
name = "xtask"
version = "0.1.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
dirs = "3.0.1"
anyhow = "1.0.36"

[dependencies.make_rs]
git = "https://github.com/Noskcaj19/make_rs"
